name: Gods
version: 0.0.2
main: com.CS4398.spc51.gods.Gods
api-version: 1.15
load: POSTWORLD
commands:
    gods:
        description: This gives information about the plugin
        usage: "Usage: /gods <page#>"
    info:
        description: This gives information about our server!
        usage: "Usage: /info <page#>"
    powerups:
        description: This gives information about powerups
        usage: "Usage: /powerups <none/list/info> <powerup>"
